dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
- cd decide
- cp local_settings.travis.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: jailuclozegc20
  strategy: git
